/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VerifySipIdRouteImport } from './routes/verify.$sipId'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSpecialistsRouteImport } from './routes/dashboard.specialists'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard.skills'
import { Route as DashboardReputationRouteImport } from './routes/dashboard.reputation'
import { Route as DashboardLedgerRouteImport } from './routes/dashboard.ledger'
import { Route as DashboardGovernanceRouteImport } from './routes/dashboard.governance'
import { Route as DashboardCommitterRouteImport } from './routes/dashboard.committer'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardAskRouteImport } from './routes/dashboard.ask'
import { Route as DashboardAdaptersRouteImport } from './routes/dashboard.adapters'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard.tasks.index'
import { Route as DashboardSpecialistsIndexRouteImport } from './routes/dashboard.specialists.index'
import { Route as DashboardSkillsIndexRouteImport } from './routes/dashboard.skills.index'
import { Route as DashboardTasksIdRouteImport } from './routes/dashboard.tasks.$id'
import { Route as DashboardSpecialistsIdRouteImport } from './routes/dashboard.specialists.$id'
import { Route as DashboardSkillsIdRouteImport } from './routes/dashboard.skills.$id'
import { Route as ApiPublicMirrorRoadmapRouteImport } from './routes/api/public/mirror-roadmap'
import { Route as ApiPublicVerifySipIdRouteImport } from './routes/api/public/verify.$sipId'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicOpenclawMcpRouteImport } from './routes/api/public/openclaw/mcp'
import { Route as ApiPublicAnchorRetryRouteImport } from './routes/api/public/anchor.retry'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VerifySipIdRoute = VerifySipIdRouteImport.update({
  id: '/verify/$sipId',
  path: '/verify/$sipId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpecialistsRoute = DashboardSpecialistsRouteImport.update({
  id: '/specialists',
  path: '/specialists',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReputationRoute = DashboardReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerRoute = DashboardLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGovernanceRoute = DashboardGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCommitterRoute = DashboardCommitterRouteImport.update({
  id: '/committer',
  path: '/committer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAskRoute = DashboardAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdaptersRoute = DashboardAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTasksRoute,
} as any)
const DashboardSpecialistsIndexRoute =
  DashboardSpecialistsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardSpecialistsRoute,
  } as any)
const DashboardSkillsIndexRoute = DashboardSkillsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSkillsRoute,
} as any)
const DashboardTasksIdRoute = DashboardTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardTasksRoute,
} as any)
const DashboardSpecialistsIdRoute = DashboardSpecialistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardSpecialistsRoute,
} as any)
const DashboardSkillsIdRoute = DashboardSkillsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardSkillsRoute,
} as any)
const ApiPublicMirrorRoadmapRoute = ApiPublicMirrorRoadmapRouteImport.update({
  id: '/api/public/mirror-roadmap',
  path: '/api/public/mirror-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifySipIdRoute = ApiPublicVerifySipIdRouteImport.update({
  id: '/api/public/verify/$sipId',
  path: '/api/public/verify/$sipId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOpenclawMcpRoute = ApiPublicOpenclawMcpRouteImport.update({
  id: '/api/public/openclaw/mcp',
  path: '/api/public/openclaw/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnchorRetryRoute = ApiPublicAnchorRetryRouteImport.update({
  id: '/api/public/anchor/retry',
  path: '/api/public/anchor/retry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/adapters': typeof DashboardAdaptersRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/committer': typeof DashboardCommitterRoute
  '/dashboard/governance': typeof DashboardGovernanceRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/dashboard/skills': typeof DashboardSkillsRouteWithChildren
  '/dashboard/specialists': typeof DashboardSpecialistsRouteWithChildren
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/verify/$sipId': typeof VerifySipIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/mirror-roadmap': typeof ApiPublicMirrorRoadmapRoute
  '/dashboard/skills/$id': typeof DashboardSkillsIdRoute
  '/dashboard/specialists/$id': typeof DashboardSpecialistsIdRoute
  '/dashboard/tasks/$id': typeof DashboardTasksIdRoute
  '/dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/dashboard/specialists/': typeof DashboardSpecialistsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/api/public/anchor/retry': typeof ApiPublicAnchorRetryRoute
  '/api/public/openclaw/mcp': typeof ApiPublicOpenclawMcpRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/verify/$sipId': typeof ApiPublicVerifySipIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/adapters': typeof DashboardAdaptersRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/committer': typeof DashboardCommitterRoute
  '/dashboard/governance': typeof DashboardGovernanceRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/verify/$sipId': typeof VerifySipIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/mirror-roadmap': typeof ApiPublicMirrorRoadmapRoute
  '/dashboard/skills/$id': typeof DashboardSkillsIdRoute
  '/dashboard/specialists/$id': typeof DashboardSpecialistsIdRoute
  '/dashboard/tasks/$id': typeof DashboardTasksIdRoute
  '/dashboard/skills': typeof DashboardSkillsIndexRoute
  '/dashboard/specialists': typeof DashboardSpecialistsIndexRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
  '/api/public/anchor/retry': typeof ApiPublicAnchorRetryRoute
  '/api/public/openclaw/mcp': typeof ApiPublicOpenclawMcpRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/verify/$sipId': typeof ApiPublicVerifySipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/adapters': typeof DashboardAdaptersRoute
  '/dashboard/ask': typeof DashboardAskRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/committer': typeof DashboardCommitterRoute
  '/dashboard/governance': typeof DashboardGovernanceRoute
  '/dashboard/ledger': typeof DashboardLedgerRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/dashboard/skills': typeof DashboardSkillsRouteWithChildren
  '/dashboard/specialists': typeof DashboardSpecialistsRouteWithChildren
  '/dashboard/tasks': typeof DashboardTasksRouteWithChildren
  '/verify/$sipId': typeof VerifySipIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/mirror-roadmap': typeof ApiPublicMirrorRoadmapRoute
  '/dashboard/skills/$id': typeof DashboardSkillsIdRoute
  '/dashboard/specialists/$id': typeof DashboardSpecialistsIdRoute
  '/dashboard/tasks/$id': typeof DashboardTasksIdRoute
  '/dashboard/skills/': typeof DashboardSkillsIndexRoute
  '/dashboard/specialists/': typeof DashboardSpecialistsIndexRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
  '/api/public/anchor/retry': typeof ApiPublicAnchorRetryRoute
  '/api/public/openclaw/mcp': typeof ApiPublicOpenclawMcpRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/verify/$sipId': typeof ApiPublicVerifySipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/api/chat'
    | '/dashboard/adapters'
    | '/dashboard/ask'
    | '/dashboard/chat'
    | '/dashboard/committer'
    | '/dashboard/governance'
    | '/dashboard/ledger'
    | '/dashboard/reputation'
    | '/dashboard/skills'
    | '/dashboard/specialists'
    | '/dashboard/tasks'
    | '/verify/$sipId'
    | '/dashboard/'
    | '/api/public/mirror-roadmap'
    | '/dashboard/skills/$id'
    | '/dashboard/specialists/$id'
    | '/dashboard/tasks/$id'
    | '/dashboard/skills/'
    | '/dashboard/specialists/'
    | '/dashboard/tasks/'
    | '/api/public/anchor/retry'
    | '/api/public/openclaw/mcp'
    | '/api/public/telegram/webhook'
    | '/api/public/verify/$sipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/api/chat'
    | '/dashboard/adapters'
    | '/dashboard/ask'
    | '/dashboard/chat'
    | '/dashboard/committer'
    | '/dashboard/governance'
    | '/dashboard/ledger'
    | '/dashboard/reputation'
    | '/verify/$sipId'
    | '/dashboard'
    | '/api/public/mirror-roadmap'
    | '/dashboard/skills/$id'
    | '/dashboard/specialists/$id'
    | '/dashboard/tasks/$id'
    | '/dashboard/skills'
    | '/dashboard/specialists'
    | '/dashboard/tasks'
    | '/api/public/anchor/retry'
    | '/api/public/openclaw/mcp'
    | '/api/public/telegram/webhook'
    | '/api/public/verify/$sipId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/api/chat'
    | '/dashboard/adapters'
    | '/dashboard/ask'
    | '/dashboard/chat'
    | '/dashboard/committer'
    | '/dashboard/governance'
    | '/dashboard/ledger'
    | '/dashboard/reputation'
    | '/dashboard/skills'
    | '/dashboard/specialists'
    | '/dashboard/tasks'
    | '/verify/$sipId'
    | '/dashboard/'
    | '/api/public/mirror-roadmap'
    | '/dashboard/skills/$id'
    | '/dashboard/specialists/$id'
    | '/dashboard/tasks/$id'
    | '/dashboard/skills/'
    | '/dashboard/specialists/'
    | '/dashboard/tasks/'
    | '/api/public/anchor/retry'
    | '/api/public/openclaw/mcp'
    | '/api/public/telegram/webhook'
    | '/api/public/verify/$sipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiChatRoute: typeof ApiChatRoute
  VerifySipIdRoute: typeof VerifySipIdRoute
  ApiPublicMirrorRoadmapRoute: typeof ApiPublicMirrorRoadmapRoute
  ApiPublicAnchorRetryRoute: typeof ApiPublicAnchorRetryRoute
  ApiPublicOpenclawMcpRoute: typeof ApiPublicOpenclawMcpRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicVerifySipIdRoute: typeof ApiPublicVerifySipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verify/$sipId': {
      id: '/verify/$sipId'
      path: '/verify/$sipId'
      fullPath: '/verify/$sipId'
      preLoaderRoute: typeof VerifySipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/specialists': {
      id: '/dashboard/specialists'
      path: '/specialists'
      fullPath: '/dashboard/specialists'
      preLoaderRoute: typeof DashboardSpecialistsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reputation': {
      id: '/dashboard/reputation'
      path: '/reputation'
      fullPath: '/dashboard/reputation'
      preLoaderRoute: typeof DashboardReputationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger': {
      id: '/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/governance': {
      id: '/dashboard/governance'
      path: '/governance'
      fullPath: '/dashboard/governance'
      preLoaderRoute: typeof DashboardGovernanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/committer': {
      id: '/dashboard/committer'
      path: '/committer'
      fullPath: '/dashboard/committer'
      preLoaderRoute: typeof DashboardCommitterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ask': {
      id: '/dashboard/ask'
      path: '/ask'
      fullPath: '/dashboard/ask'
      preLoaderRoute: typeof DashboardAskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/adapters': {
      id: '/dashboard/adapters'
      path: '/adapters'
      fullPath: '/dashboard/adapters'
      preLoaderRoute: typeof DashboardAdaptersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
    '/dashboard/specialists/': {
      id: '/dashboard/specialists/'
      path: '/'
      fullPath: '/dashboard/specialists/'
      preLoaderRoute: typeof DashboardSpecialistsIndexRouteImport
      parentRoute: typeof DashboardSpecialistsRoute
    }
    '/dashboard/skills/': {
      id: '/dashboard/skills/'
      path: '/'
      fullPath: '/dashboard/skills/'
      preLoaderRoute: typeof DashboardSkillsIndexRouteImport
      parentRoute: typeof DashboardSkillsRoute
    }
    '/dashboard/tasks/$id': {
      id: '/dashboard/tasks/$id'
      path: '/$id'
      fullPath: '/dashboard/tasks/$id'
      preLoaderRoute: typeof DashboardTasksIdRouteImport
      parentRoute: typeof DashboardTasksRoute
    }
    '/dashboard/specialists/$id': {
      id: '/dashboard/specialists/$id'
      path: '/$id'
      fullPath: '/dashboard/specialists/$id'
      preLoaderRoute: typeof DashboardSpecialistsIdRouteImport
      parentRoute: typeof DashboardSpecialistsRoute
    }
    '/dashboard/skills/$id': {
      id: '/dashboard/skills/$id'
      path: '/$id'
      fullPath: '/dashboard/skills/$id'
      preLoaderRoute: typeof DashboardSkillsIdRouteImport
      parentRoute: typeof DashboardSkillsRoute
    }
    '/api/public/mirror-roadmap': {
      id: '/api/public/mirror-roadmap'
      path: '/api/public/mirror-roadmap'
      fullPath: '/api/public/mirror-roadmap'
      preLoaderRoute: typeof ApiPublicMirrorRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify/$sipId': {
      id: '/api/public/verify/$sipId'
      path: '/api/public/verify/$sipId'
      fullPath: '/api/public/verify/$sipId'
      preLoaderRoute: typeof ApiPublicVerifySipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openclaw/mcp': {
      id: '/api/public/openclaw/mcp'
      path: '/api/public/openclaw/mcp'
      fullPath: '/api/public/openclaw/mcp'
      preLoaderRoute: typeof ApiPublicOpenclawMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/anchor/retry': {
      id: '/api/public/anchor/retry'
      path: '/api/public/anchor/retry'
      fullPath: '/api/public/anchor/retry'
      preLoaderRoute: typeof ApiPublicAnchorRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSkillsRouteChildren {
  DashboardSkillsIdRoute: typeof DashboardSkillsIdRoute
  DashboardSkillsIndexRoute: typeof DashboardSkillsIndexRoute
}

const DashboardSkillsRouteChildren: DashboardSkillsRouteChildren = {
  DashboardSkillsIdRoute: DashboardSkillsIdRoute,
  DashboardSkillsIndexRoute: DashboardSkillsIndexRoute,
}

const DashboardSkillsRouteWithChildren = DashboardSkillsRoute._addFileChildren(
  DashboardSkillsRouteChildren,
)

interface DashboardSpecialistsRouteChildren {
  DashboardSpecialistsIdRoute: typeof DashboardSpecialistsIdRoute
  DashboardSpecialistsIndexRoute: typeof DashboardSpecialistsIndexRoute
}

const DashboardSpecialistsRouteChildren: DashboardSpecialistsRouteChildren = {
  DashboardSpecialistsIdRoute: DashboardSpecialistsIdRoute,
  DashboardSpecialistsIndexRoute: DashboardSpecialistsIndexRoute,
}

const DashboardSpecialistsRouteWithChildren =
  DashboardSpecialistsRoute._addFileChildren(DashboardSpecialistsRouteChildren)

interface DashboardTasksRouteChildren {
  DashboardTasksIdRoute: typeof DashboardTasksIdRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
}

const DashboardTasksRouteChildren: DashboardTasksRouteChildren = {
  DashboardTasksIdRoute: DashboardTasksIdRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
}

const DashboardTasksRouteWithChildren = DashboardTasksRoute._addFileChildren(
  DashboardTasksRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdaptersRoute: typeof DashboardAdaptersRoute
  DashboardAskRoute: typeof DashboardAskRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardCommitterRoute: typeof DashboardCommitterRoute
  DashboardGovernanceRoute: typeof DashboardGovernanceRoute
  DashboardLedgerRoute: typeof DashboardLedgerRoute
  DashboardReputationRoute: typeof DashboardReputationRoute
  DashboardSkillsRoute: typeof DashboardSkillsRouteWithChildren
  DashboardSpecialistsRoute: typeof DashboardSpecialistsRouteWithChildren
  DashboardTasksRoute: typeof DashboardTasksRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdaptersRoute: DashboardAdaptersRoute,
  DashboardAskRoute: DashboardAskRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardCommitterRoute: DashboardCommitterRoute,
  DashboardGovernanceRoute: DashboardGovernanceRoute,
  DashboardLedgerRoute: DashboardLedgerRoute,
  DashboardReputationRoute: DashboardReputationRoute,
  DashboardSkillsRoute: DashboardSkillsRouteWithChildren,
  DashboardSpecialistsRoute: DashboardSpecialistsRouteWithChildren,
  DashboardTasksRoute: DashboardTasksRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiChatRoute: ApiChatRoute,
  VerifySipIdRoute: VerifySipIdRoute,
  ApiPublicMirrorRoadmapRoute: ApiPublicMirrorRoadmapRoute,
  ApiPublicAnchorRetryRoute: ApiPublicAnchorRetryRoute,
  ApiPublicOpenclawMcpRoute: ApiPublicOpenclawMcpRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicVerifySipIdRoute: ApiPublicVerifySipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
